# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x10helloworld.proto\x12\nhelloworld\"\x16\n\x06Number\x12\x0c\n\x04size\x18\x01 \x01(\x05\" \n\rRegistration2\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bPrevServer2\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bTransaction\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x05\x42lock\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cTransactions\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x06\x42locks\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cRegistration\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nPrevServer\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tHandshake\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rKnownPeerList\x12\x0f\n\x07message\x18\x01 \x03(\t\"\x17\n\x04Peer\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x05\x42lank\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc5\x05\n\x07Greeter\x12\x46\n\x10SendRegistration\x12\x18.helloworld.Registration\x1a\x16.helloworld.PrevServer\"\x00\x12\x43\n\rSendHandshake\x12\x15.helloworld.Handshake\x1a\x19.helloworld.KnownPeerList\"\x00\x12\x31\n\x08SendPeer\x12\x10.helloworld.Peer\x1a\x11.helloworld.Blank\"\x00\x12;\n\tPullPeers\x12\x11.helloworld.Blank\x1a\x19.helloworld.KnownPeerList\"\x00\x12\x44\n\x14\x42roadcastTransaction\x12\x17.helloworld.Transaction\x1a\x11.helloworld.Blank\"\x00\x12\x38\n\x0e\x42roadcastBlock\x12\x11.helloworld.Block\x1a\x11.helloworld.Blank\"\x00\x12\x41\n\x10PullTransactions\x12\x11.helloworld.Blank\x1a\x18.helloworld.Transactions\"\x00\x12\x35\n\nPullBlocks\x12\x11.helloworld.Blank\x1a\x12.helloworld.Blocks\"\x00\x12>\n\x13PullTransactionSize\x12\x11.helloworld.Blank\x1a\x12.helloworld.Number\"\x00\x12\x38\n\rPullBlockSize\x12\x11.helloworld.Blank\x1a\x12.helloworld.Number\"\x00\x12I\n\x11SendRegistration2\x12\x19.helloworld.Registration2\x1a\x17.helloworld.PrevServer2\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='helloworld.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='helloworld.Number.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=54,
)


_REGISTRATION2 = _descriptor.Descriptor(
  name='Registration2',
  full_name='helloworld.Registration2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Registration2.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=88,
)


_PREVSERVER2 = _descriptor.Descriptor(
  name='PrevServer2',
  full_name='helloworld.PrevServer2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.PrevServer2.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=120,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='helloworld.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Transaction.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=152,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='helloworld.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Block.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=178,
)


_TRANSACTIONS = _descriptor.Descriptor(
  name='Transactions',
  full_name='helloworld.Transactions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Transactions.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=211,
)


_BLOCKS = _descriptor.Descriptor(
  name='Blocks',
  full_name='helloworld.Blocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Blocks.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=238,
)


_REGISTRATION = _descriptor.Descriptor(
  name='Registration',
  full_name='helloworld.Registration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Registration.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=271,
)


_PREVSERVER = _descriptor.Descriptor(
  name='PrevServer',
  full_name='helloworld.PrevServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.PrevServer.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=302,
)


_HANDSHAKE = _descriptor.Descriptor(
  name='Handshake',
  full_name='helloworld.Handshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Handshake.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=332,
)


_KNOWNPEERLIST = _descriptor.Descriptor(
  name='KnownPeerList',
  full_name='helloworld.KnownPeerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.KnownPeerList.message', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=366,
)


_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='helloworld.Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Peer.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=391,
)


_BLANK = _descriptor.Descriptor(
  name='Blank',
  full_name='helloworld.Blank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.Blank.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=417,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Registration2'] = _REGISTRATION2
DESCRIPTOR.message_types_by_name['PrevServer2'] = _PREVSERVER2
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Transactions'] = _TRANSACTIONS
DESCRIPTOR.message_types_by_name['Blocks'] = _BLOCKS
DESCRIPTOR.message_types_by_name['Registration'] = _REGISTRATION
DESCRIPTOR.message_types_by_name['PrevServer'] = _PREVSERVER
DESCRIPTOR.message_types_by_name['Handshake'] = _HANDSHAKE
DESCRIPTOR.message_types_by_name['KnownPeerList'] = _KNOWNPEERLIST
DESCRIPTOR.message_types_by_name['Peer'] = _PEER
DESCRIPTOR.message_types_by_name['Blank'] = _BLANK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Number)
  ))
_sym_db.RegisterMessage(Number)

Registration2 = _reflection.GeneratedProtocolMessageType('Registration2', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATION2,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Registration2)
  ))
_sym_db.RegisterMessage(Registration2)

PrevServer2 = _reflection.GeneratedProtocolMessageType('PrevServer2', (_message.Message,), dict(
  DESCRIPTOR = _PREVSERVER2,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PrevServer2)
  ))
_sym_db.RegisterMessage(PrevServer2)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Block)
  ))
_sym_db.RegisterMessage(Block)

Transactions = _reflection.GeneratedProtocolMessageType('Transactions', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONS,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Transactions)
  ))
_sym_db.RegisterMessage(Transactions)

Blocks = _reflection.GeneratedProtocolMessageType('Blocks', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKS,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Blocks)
  ))
_sym_db.RegisterMessage(Blocks)

Registration = _reflection.GeneratedProtocolMessageType('Registration', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATION,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Registration)
  ))
_sym_db.RegisterMessage(Registration)

PrevServer = _reflection.GeneratedProtocolMessageType('PrevServer', (_message.Message,), dict(
  DESCRIPTOR = _PREVSERVER,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PrevServer)
  ))
_sym_db.RegisterMessage(PrevServer)

Handshake = _reflection.GeneratedProtocolMessageType('Handshake', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKE,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Handshake)
  ))
_sym_db.RegisterMessage(Handshake)

KnownPeerList = _reflection.GeneratedProtocolMessageType('KnownPeerList', (_message.Message,), dict(
  DESCRIPTOR = _KNOWNPEERLIST,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.KnownPeerList)
  ))
_sym_db.RegisterMessage(KnownPeerList)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), dict(
  DESCRIPTOR = _PEER,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Peer)
  ))
_sym_db.RegisterMessage(Peer)

Blank = _reflection.GeneratedProtocolMessageType('Blank', (_message.Message,), dict(
  DESCRIPTOR = _BLANK,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Blank)
  ))
_sym_db.RegisterMessage(Blank)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=420,
  serialized_end=1129,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendRegistration',
    full_name='helloworld.Greeter.SendRegistration',
    index=0,
    containing_service=None,
    input_type=_REGISTRATION,
    output_type=_PREVSERVER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendHandshake',
    full_name='helloworld.Greeter.SendHandshake',
    index=1,
    containing_service=None,
    input_type=_HANDSHAKE,
    output_type=_KNOWNPEERLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPeer',
    full_name='helloworld.Greeter.SendPeer',
    index=2,
    containing_service=None,
    input_type=_PEER,
    output_type=_BLANK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullPeers',
    full_name='helloworld.Greeter.PullPeers',
    index=3,
    containing_service=None,
    input_type=_BLANK,
    output_type=_KNOWNPEERLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BroadcastTransaction',
    full_name='helloworld.Greeter.BroadcastTransaction',
    index=4,
    containing_service=None,
    input_type=_TRANSACTION,
    output_type=_BLANK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BroadcastBlock',
    full_name='helloworld.Greeter.BroadcastBlock',
    index=5,
    containing_service=None,
    input_type=_BLOCK,
    output_type=_BLANK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullTransactions',
    full_name='helloworld.Greeter.PullTransactions',
    index=6,
    containing_service=None,
    input_type=_BLANK,
    output_type=_TRANSACTIONS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullBlocks',
    full_name='helloworld.Greeter.PullBlocks',
    index=7,
    containing_service=None,
    input_type=_BLANK,
    output_type=_BLOCKS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullTransactionSize',
    full_name='helloworld.Greeter.PullTransactionSize',
    index=8,
    containing_service=None,
    input_type=_BLANK,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullBlockSize',
    full_name='helloworld.Greeter.PullBlockSize',
    index=9,
    containing_service=None,
    input_type=_BLANK,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendRegistration2',
    full_name='helloworld.Greeter.SendRegistration2',
    index=10,
    containing_service=None,
    input_type=_REGISTRATION2,
    output_type=_PREVSERVER2,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
