# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendRegistration = channel.unary_unary(
        '/helloworld.Greeter/SendRegistration',
        request_serializer=helloworld__pb2.Registration.SerializeToString,
        response_deserializer=helloworld__pb2.PrevServer.FromString,
        )
    self.SendHandshake = channel.unary_unary(
        '/helloworld.Greeter/SendHandshake',
        request_serializer=helloworld__pb2.Handshake.SerializeToString,
        response_deserializer=helloworld__pb2.KnownPeerList.FromString,
        )
    self.SendPeer = channel.unary_unary(
        '/helloworld.Greeter/SendPeer',
        request_serializer=helloworld__pb2.Peer.SerializeToString,
        response_deserializer=helloworld__pb2.Blank.FromString,
        )
    self.PullPeers = channel.unary_unary(
        '/helloworld.Greeter/PullPeers',
        request_serializer=helloworld__pb2.Blank.SerializeToString,
        response_deserializer=helloworld__pb2.KnownPeerList.FromString,
        )
    self.BroadcastTransaction = channel.unary_unary(
        '/helloworld.Greeter/BroadcastTransaction',
        request_serializer=helloworld__pb2.Transaction.SerializeToString,
        response_deserializer=helloworld__pb2.Blank.FromString,
        )
    self.BroadcastBlock = channel.unary_unary(
        '/helloworld.Greeter/BroadcastBlock',
        request_serializer=helloworld__pb2.Block.SerializeToString,
        response_deserializer=helloworld__pb2.Blank.FromString,
        )
    self.PullTransactions = channel.unary_unary(
        '/helloworld.Greeter/PullTransactions',
        request_serializer=helloworld__pb2.Blank.SerializeToString,
        response_deserializer=helloworld__pb2.Transactions.FromString,
        )
    self.PullBlocks = channel.unary_unary(
        '/helloworld.Greeter/PullBlocks',
        request_serializer=helloworld__pb2.Blank.SerializeToString,
        response_deserializer=helloworld__pb2.Blocks.FromString,
        )
    self.PullTransactionSize = channel.unary_unary(
        '/helloworld.Greeter/PullTransactionSize',
        request_serializer=helloworld__pb2.Blank.SerializeToString,
        response_deserializer=helloworld__pb2.Number.FromString,
        )
    self.PullBlockSize = channel.unary_unary(
        '/helloworld.Greeter/PullBlockSize',
        request_serializer=helloworld__pb2.Blank.SerializeToString,
        response_deserializer=helloworld__pb2.Number.FromString,
        )
    self.SendRegistration2 = channel.unary_unary(
        '/helloworld.Greeter/SendRegistration2',
        request_serializer=helloworld__pb2.Registration2.SerializeToString,
        response_deserializer=helloworld__pb2.PrevServer2.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def SendRegistration(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendHandshake(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendPeer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PullPeers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BroadcastTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BroadcastBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PullTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PullBlocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PullTransactionSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PullBlockSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendRegistration2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendRegistration': grpc.unary_unary_rpc_method_handler(
          servicer.SendRegistration,
          request_deserializer=helloworld__pb2.Registration.FromString,
          response_serializer=helloworld__pb2.PrevServer.SerializeToString,
      ),
      'SendHandshake': grpc.unary_unary_rpc_method_handler(
          servicer.SendHandshake,
          request_deserializer=helloworld__pb2.Handshake.FromString,
          response_serializer=helloworld__pb2.KnownPeerList.SerializeToString,
      ),
      'SendPeer': grpc.unary_unary_rpc_method_handler(
          servicer.SendPeer,
          request_deserializer=helloworld__pb2.Peer.FromString,
          response_serializer=helloworld__pb2.Blank.SerializeToString,
      ),
      'PullPeers': grpc.unary_unary_rpc_method_handler(
          servicer.PullPeers,
          request_deserializer=helloworld__pb2.Blank.FromString,
          response_serializer=helloworld__pb2.KnownPeerList.SerializeToString,
      ),
      'BroadcastTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.BroadcastTransaction,
          request_deserializer=helloworld__pb2.Transaction.FromString,
          response_serializer=helloworld__pb2.Blank.SerializeToString,
      ),
      'BroadcastBlock': grpc.unary_unary_rpc_method_handler(
          servicer.BroadcastBlock,
          request_deserializer=helloworld__pb2.Block.FromString,
          response_serializer=helloworld__pb2.Blank.SerializeToString,
      ),
      'PullTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.PullTransactions,
          request_deserializer=helloworld__pb2.Blank.FromString,
          response_serializer=helloworld__pb2.Transactions.SerializeToString,
      ),
      'PullBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.PullBlocks,
          request_deserializer=helloworld__pb2.Blank.FromString,
          response_serializer=helloworld__pb2.Blocks.SerializeToString,
      ),
      'PullTransactionSize': grpc.unary_unary_rpc_method_handler(
          servicer.PullTransactionSize,
          request_deserializer=helloworld__pb2.Blank.FromString,
          response_serializer=helloworld__pb2.Number.SerializeToString,
      ),
      'PullBlockSize': grpc.unary_unary_rpc_method_handler(
          servicer.PullBlockSize,
          request_deserializer=helloworld__pb2.Blank.FromString,
          response_serializer=helloworld__pb2.Number.SerializeToString,
      ),
      'SendRegistration2': grpc.unary_unary_rpc_method_handler(
          servicer.SendRegistration2,
          request_deserializer=helloworld__pb2.Registration2.FromString,
          response_serializer=helloworld__pb2.PrevServer2.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
